# Generated by Django 4.1.2 on 2022-10-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="generator",
            new_name="is_auto_generated",
        ),
    ]
