# Generated by Django 4.1.2 on 2022-10-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_rename_generator_contact_is_auto_generated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="b_day",
            field=models.DateField(),
        ),
    ]
