# Generated by Django 4.1.2 on 2022-10-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_alter_contact_b_day"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("-created_at",)},
        ),
    ]
