# Generated by Django 4.1.2 on 2022-10-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_contact_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
    ]
