# Generated by Django 4.1.3 on 2022-11-18 14:37

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0006_contact_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="avatar",
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=contacts.models.get_icon_path),
        ),
    ]
