# Generated by Django 4.1.3 on 2022-12-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("middlewares", "0002_alter_visitorsrequests_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visitorsrequests",
            old_name="visits_count",
            new_name="count_of_visits",
        ),
    ]
