# Generated by Django 4.1.3 on 2022-11-21 15:04

from django.db import migrations, models
import users_admin.models


class Migration(migrations.Migration):
    dependencies = [
        ("users_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="avatar",
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=users_admin.models.get_user_icon_path),
        ),
    ]
